# Generated by Django 5.2.7 on 2025-10-28 19:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emp_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="hire_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="person",
            name="phone",
            field=models.IntegerField(default=0),
        ),
    ]
